### PR TITLE
added development page

### PR DESCRIPTION
**Pull request by tracykteal**
still need to add more content, but it's a page that had a pointer to our github repo

### CODE REVIEW

**Comment by karthik** [comment]
Can you post a screenshot here in the comments? (You can paste directly in comments here from clipboard).

**Comment by tracykteal** [comment]
screen shot 2015-04-16 at 7 14 42 pm

**Comment by tracykteal** [comment]
Lessons page:

screen shot 2015-04-16 at 7 16 19 pm

**Comment by tracykteal** [comment]
Neither is the final version, but are better than just pointing to our github repo, while we get lesson-templates in place that will be available as web sites like http://datacarpentry.github.io/python-ecology/
I put a template like that in the lesson-template repo. And once we've adopted a template, updating the CONTRIBUTING.md file, and that can also be on this page.

**Comment by ethanwhite** [comment]
Looks like a good improvement to me. +1.

**Pull request merged**
